### ISSUE TITLE
Viewing Vignette

### ISSUE THREAD

**Issue by grasskind** [marcalva/diem#1]
Is there a way to view the vignette from R? When I list the available vignette's there isn't one listed for diem.

**Comment by marcalva** [comment]
Hi,
Are you using the vignette() function from utils? Also, after installing the package, is the doc/diem.html present?
Thanks,
Marcus

**Comment by grasskind** [comment]
Hi Marcus, 

I am using the vignette() function. library("diem") followed by vignette("diem") returns "vignette ‘diem’ not found". I also tried vignette(all = FALSE) to see if the name was different, but nothing showed up for diem. 

There is no doc/diem.html in the package folder (there is no doc folder). There is an html/diem.html, but this gives the function description rather than a vignette. 

Best,
Greg

**Comment by marcalva** [comment]
Hi Greg,

I think the problem is that the vignette isn't being built with diem, and there is no doc folder. I'm not sure why this is the case, but I found a workaround that may solve this for now.

Try directly downloading the diem repository:
`git clone https://github.com/marcalva/diem.git`

Install the package from source directly. One way that worked for me was to run devtools install within the diem directory with `build_vignette=TRUE`:
```R
library(devtools)
devtools::install(build_vignette=TRUE)
```

Hope this helps!
Thanks,
Marcus

**Comment by grasskind** [comment]
Hi Marcus,

Installing with build_vignette=TRUE did the trick. Thank you!

Best,
Greg

**Comment by marcalva** [comment]
Good to hear!
Best,
Marcus
